server:
  port: 8089
  context-path: /pay

spring:
   application:
      name: cloud-pay-service-856

   datasource:
        name: test
        url: jdbc:mysql://192.168.8.206:3306/parking?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: root
        #此处密码待加密存放
        password: abc_123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

   redis:
        database: 0
        host: 192.168.8.89
        port: 6379
        password: abc_123456
        timeout: 30000
        pool:
          max-active: 100
          max-idle: 200
          min-idle: 200
          max-wait: 10000
    #i18n
   messages:
      basename: message
   
   data:
       mongodb:
         uri: mongodb://192.168.8.89:27017/device_db
         database: device_db
         host: 192.168.8.89
         port: 27017
      
logging:
    pattern:
      console: "%-5level-%thread-%d- %msg%n"
    level:
        com.drzk.pay: debug
    file: /nasdir/log/payment/manager.log

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.drzk.pay.mapper

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    
eureka: 
  client: 
     serviceUrl: 
        defaultZone: http://wolf:abc123@192.168.8.89:8088/eureka/
     healthcheck: 
        enabled: true
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30


drzk-mqtt: 
  mqttServer: tcp://192.168.8.208:1883
  --mqttServer: tcp://192.168.8.89:1883
  mqttUserName: admin
  mqttPwd: public
  pubTopics: 
  subTopics: getPayment/wechat,getPayment/alipay
  qos: 2
  sendClientId: drzk-client-pay2-851
  receiveClintId: drzk-client-pay3-851
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000  